import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/component/global/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full bg-white">
      <body
        className={
          inter.className +
          " h-full overflow-hidden bg-stone-100 text-stone-900"
        }
      >
        {children}
      </body>
    </html>
  );
}
